line-length = 120
target-version = "py311"
cache-dir = "./.ruff_cache"
src = ["backend/app",]
[lint]
select = [
    "E",
    "F",
    "I",
    "W505",
    "SIM101",
    "SIM114",
    "PGH004",
    "PLE1142",
    "RUF100",
    "F404",
    "TCH",
    "UP007"
]

ignore = [
    "ERA001",
]

exclude = [
    '.cache',
    '.git',
    '.idea',
    '.mypy_cache',
    '.pytest_cache',
    '.venv',
    'venv',
    'env',
    'cached_venv',
    'docs',
    'deploy',
    'var',
    '.vscode',
    '*migrations*',
    'filebeat*'
]

[lint.isort]
lines-between-types = 1
order-by-type = true
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[lint.per-file-ignores]
"backend/app/api/v1/*.py" = ["TCH"]
"backend/app/models/*.py" = ["TCH003"]
"backend/app/**/__init__.py" = ["F401"]

[format]
quote-style = "single"
preview = true
